
public class TestException {

	public static void main(String[] args) {
		int a = 10;
		int b = 0;
		int c = 0;
		try {
			c =a/b;
		}catch (ArithmeticException ae){
			System.out.println(ae.getMessage());
		}//catch
		System.out.println(c);
		System.err.println();
	}//main

}//class  TestException
